# Generated by Django 2.2.4 on 2019-08-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_heading', models.CharField(default='Project', max_length=10)),
                ('title', models.CharField(default='Project Title', max_length=150)),
                ('thumbnail', models.ImageField(null=True, upload_to='images/project/thumbnail')),
            ],
        ),
    ]
