# Generated by Django 2.2.4 on 2019-08-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='About', max_length=20)),
                ('detail_heading', models.CharField(default='Peronal Details', max_length=20)),
                ('short_detail', models.TextField(default='Lorem Ipsum is simply or ceturies.')),
                ('name', models.CharField(default='Ashish Shrestha', max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('location', models.CharField(default='Kaushaltar, Bhaktapur', max_length=100)),
                ('skill_heading', models.CharField(default='My Skills', max_length=25)),
                ('skill_one', models.CharField(default='Python', max_length=25)),
                ('skill_one_level', models.IntegerField(default='80')),
                ('skill_two', models.CharField(default='React & Redux', max_length=25)),
                ('skill_two_level', models.IntegerField(default='80')),
                ('skill_three', models.CharField(default='Embedded System Design', max_length=25)),
                ('skill_three_level', models.IntegerField(default='80')),
                ('skill_four', models.CharField(default='Machine Learning', max_length=25)),
                ('skill_four_level', models.IntegerField(default='80')),
                ('interest_one_title', models.CharField(default='Research', max_length=20)),
                ('interest_one_detail', models.TextField()),
                ('interest_two_title', models.CharField(default='Design', max_length=20)),
                ('interest_two_detail', models.TextField()),
                ('interest_three_title', models.CharField(default='Development', max_length=20)),
                ('interest_three_detail', models.TextField()),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About Pages',
            },
        ),
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Portfolio', max_length=30)),
                ('introduction', models.CharField(default="Hello, It's Name Surname", max_length=150)),
                ('who_you_are', models.CharField(default="I'm ", max_length=20)),
                ('first_skill', models.CharField(default='a Developer.', max_length=30)),
                ('second_skill', models.CharField(default='an Electronics Engineer.', max_length=30)),
                ('third_skill', models.CharField(default='a Freelancer.', max_length=30)),
                ('fourth_skill', models.CharField(blank=True, default='optional field', max_length=30, null=True)),
                ('short_description', models.TextField(default='It is a long orem ipsum', null=True)),
                ('button_text', models.CharField(default='Hire Me Now!', max_length=15)),
                ('banner_image', models.ImageField(null=True, upload_to='images/banner')),
            ],
            options={
                'verbose_name': 'Landing',
                'verbose_name_plural': 'Landing Pages',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='Steve Jobs', max_length=50)),
                ('quotes', models.TextField(default='Design is not just what it looks like and feels like. Design is how it works')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg_icon', models.FileField(blank=True, null=True, upload_to='images/services/icon')),
                ('service_name', models.CharField(default='Web Design', max_length=20)),
                ('service_description', models.CharField(default='Lorem ipsum is simply dummy', max_length=180)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(default='https://facebook.com', max_length=50)),
                ('twitter', models.CharField(default='https://www.twitter.com', max_length=50)),
                ('instagram', models.CharField(default='https://www.instagram.com', max_length=50)),
                ('github_link', models.CharField(default='https://www.github.com', max_length=50)),
                ('linkedin', models.CharField(default='https://linkedin.com', max_length=50)),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Omar Hampton', max_length=50)),
                ('designation', models.CharField(default='Chief Executive Officer', max_length=50)),
                ('company', models.CharField(blank=True, default='Metrotarkari Pvt Ltd', max_length=50)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/testimonials')),
            ],
            options={
                'verbose_name': 'testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
